// Code generated by ent, DO NOT EDIT.

package tblgarageowner

import (
	"rr-backend/ent/entgen/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldID, id))
}

// CreatedBy applies equality check predicate on the "CreatedBy" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "UpdatedBy" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "DeletedBy" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldDeletedBy, v))
}

// IP applies equality check predicate on the "IP" field. It's identical to IPEQ.
func IP(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldIP, v))
}

// UserAgent applies equality check predicate on the "UserAgent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "CreatedAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "UpdatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "DeletedAt" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldDeletedAt, v))
}

// UserIdUlid applies equality check predicate on the "UserId_ulid" field. It's identical to UserIdUlidEQ.
func UserIdUlid(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUserIdUlid, v))
}

// Initial applies equality check predicate on the "Initial" field. It's identical to InitialEQ.
func Initial(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldInitial, v))
}

// FirstName applies equality check predicate on the "FirstName" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldFirstName, v))
}

// MiddleName applies equality check predicate on the "MiddleName" field. It's identical to MiddleNameEQ.
func MiddleName(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldMiddleName, v))
}

// LastName applies equality check predicate on the "LastName" field. It's identical to LastNameEQ.
func LastName(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldLastName, v))
}

// ContactNumber applies equality check predicate on the "ContactNumber" field. It's identical to ContactNumberEQ.
func ContactNumber(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldContactNumber, v))
}

// Email applies equality check predicate on the "Email" field. It's identical to EmailEQ.
func Email(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldEmail, v))
}

// Age applies equality check predicate on the "Age" field. It's identical to AgeEQ.
func Age(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldAge, v))
}

// PhotoIdUlid applies equality check predicate on the "PhotoId_ulid" field. It's identical to PhotoIdUlidEQ.
func PhotoIdUlid(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldPhotoIdUlid, v))
}

// AddressIdUlid applies equality check predicate on the "AddressId_ulid" field. It's identical to AddressIdUlidEQ.
func AddressIdUlid(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldAddressIdUlid, v))
}

// CreatedByEQ applies the EQ predicate on the "CreatedBy" field.
func CreatedByEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "CreatedBy" field.
func CreatedByNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "CreatedBy" field.
func CreatedByIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "CreatedBy" field.
func CreatedByNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "CreatedBy" field.
func CreatedByGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "CreatedBy" field.
func CreatedByGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "CreatedBy" field.
func CreatedByLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "CreatedBy" field.
func CreatedByLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "CreatedBy" field.
func CreatedByContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "CreatedBy" field.
func CreatedByHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "CreatedBy" field.
func CreatedByHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "CreatedBy" field.
func CreatedByIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "CreatedBy" field.
func CreatedByNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "CreatedBy" field.
func CreatedByEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "CreatedBy" field.
func CreatedByContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "UpdatedBy" field.
func UpdatedByEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "UpdatedBy" field.
func UpdatedByNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "UpdatedBy" field.
func UpdatedByIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "UpdatedBy" field.
func UpdatedByNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "UpdatedBy" field.
func UpdatedByGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "UpdatedBy" field.
func UpdatedByGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "UpdatedBy" field.
func UpdatedByLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "UpdatedBy" field.
func UpdatedByLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "UpdatedBy" field.
func UpdatedByContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "UpdatedBy" field.
func UpdatedByHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "UpdatedBy" field.
func UpdatedByHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "UpdatedBy" field.
func UpdatedByIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "UpdatedBy" field.
func UpdatedByNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "UpdatedBy" field.
func UpdatedByEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "UpdatedBy" field.
func UpdatedByContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedByEQ applies the EQ predicate on the "DeletedBy" field.
func DeletedByEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "DeletedBy" field.
func DeletedByNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "DeletedBy" field.
func DeletedByIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "DeletedBy" field.
func DeletedByNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "DeletedBy" field.
func DeletedByGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "DeletedBy" field.
func DeletedByGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "DeletedBy" field.
func DeletedByLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "DeletedBy" field.
func DeletedByLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "DeletedBy" field.
func DeletedByContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "DeletedBy" field.
func DeletedByHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "DeletedBy" field.
func DeletedByHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "DeletedBy" field.
func DeletedByIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "DeletedBy" field.
func DeletedByNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "DeletedBy" field.
func DeletedByEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "DeletedBy" field.
func DeletedByContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldDeletedBy, v))
}

// IPEQ applies the EQ predicate on the "IP" field.
func IPEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "IP" field.
func IPNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "IP" field.
func IPIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "IP" field.
func IPNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "IP" field.
func IPGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "IP" field.
func IPGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "IP" field.
func IPLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "IP" field.
func IPLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "IP" field.
func IPContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "IP" field.
func IPHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "IP" field.
func IPHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldIP, v))
}

// IPIsNil applies the IsNil predicate on the "IP" field.
func IPIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldIP))
}

// IPNotNil applies the NotNil predicate on the "IP" field.
func IPNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldIP))
}

// IPEqualFold applies the EqualFold predicate on the "IP" field.
func IPEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "IP" field.
func IPContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldIP, v))
}

// UserAgentEQ applies the EQ predicate on the "UserAgent" field.
func UserAgentEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "UserAgent" field.
func UserAgentNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "UserAgent" field.
func UserAgentIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "UserAgent" field.
func UserAgentNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "UserAgent" field.
func UserAgentGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "UserAgent" field.
func UserAgentGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "UserAgent" field.
func UserAgentLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "UserAgent" field.
func UserAgentLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "UserAgent" field.
func UserAgentContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "UserAgent" field.
func UserAgentHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "UserAgent" field.
func UserAgentHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "UserAgent" field.
func UserAgentIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "UserAgent" field.
func UserAgentNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "UserAgent" field.
func UserAgentEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "UserAgent" field.
func UserAgentContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "CreatedAt" field.
func CreatedAtEQ(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "CreatedAt" field.
func CreatedAtNEQ(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "CreatedAt" field.
func CreatedAtIn(vs ...time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "CreatedAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "CreatedAt" field.
func CreatedAtGT(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "CreatedAt" field.
func CreatedAtGTE(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "CreatedAt" field.
func CreatedAtLT(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "CreatedAt" field.
func CreatedAtLTE(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "UpdatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "UpdatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "UpdatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "UpdatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "UpdatedAt" field.
func UpdatedAtGT(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "UpdatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "UpdatedAt" field.
func UpdatedAtLT(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "UpdatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "DeletedAt" field.
func DeletedAtEQ(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "DeletedAt" field.
func DeletedAtNEQ(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "DeletedAt" field.
func DeletedAtIn(vs ...time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "DeletedAt" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "DeletedAt" field.
func DeletedAtGT(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "DeletedAt" field.
func DeletedAtGTE(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "DeletedAt" field.
func DeletedAtLT(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "DeletedAt" field.
func DeletedAtLTE(v time.Time) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "DeletedAt" field.
func DeletedAtIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "DeletedAt" field.
func DeletedAtNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldDeletedAt))
}

// UserIdUlidEQ applies the EQ predicate on the "UserId_ulid" field.
func UserIdUlidEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldUserIdUlid, v))
}

// UserIdUlidNEQ applies the NEQ predicate on the "UserId_ulid" field.
func UserIdUlidNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldUserIdUlid, v))
}

// UserIdUlidIn applies the In predicate on the "UserId_ulid" field.
func UserIdUlidIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldUserIdUlid, vs...))
}

// UserIdUlidNotIn applies the NotIn predicate on the "UserId_ulid" field.
func UserIdUlidNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldUserIdUlid, vs...))
}

// UserIdUlidGT applies the GT predicate on the "UserId_ulid" field.
func UserIdUlidGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldUserIdUlid, v))
}

// UserIdUlidGTE applies the GTE predicate on the "UserId_ulid" field.
func UserIdUlidGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldUserIdUlid, v))
}

// UserIdUlidLT applies the LT predicate on the "UserId_ulid" field.
func UserIdUlidLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldUserIdUlid, v))
}

// UserIdUlidLTE applies the LTE predicate on the "UserId_ulid" field.
func UserIdUlidLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldUserIdUlid, v))
}

// UserIdUlidContains applies the Contains predicate on the "UserId_ulid" field.
func UserIdUlidContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldUserIdUlid, v))
}

// UserIdUlidHasPrefix applies the HasPrefix predicate on the "UserId_ulid" field.
func UserIdUlidHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldUserIdUlid, v))
}

// UserIdUlidHasSuffix applies the HasSuffix predicate on the "UserId_ulid" field.
func UserIdUlidHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldUserIdUlid, v))
}

// UserIdUlidIsNil applies the IsNil predicate on the "UserId_ulid" field.
func UserIdUlidIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldUserIdUlid))
}

// UserIdUlidNotNil applies the NotNil predicate on the "UserId_ulid" field.
func UserIdUlidNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldUserIdUlid))
}

// UserIdUlidEqualFold applies the EqualFold predicate on the "UserId_ulid" field.
func UserIdUlidEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldUserIdUlid, v))
}

// UserIdUlidContainsFold applies the ContainsFold predicate on the "UserId_ulid" field.
func UserIdUlidContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldUserIdUlid, v))
}

// InitialEQ applies the EQ predicate on the "Initial" field.
func InitialEQ(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldInitial, v))
}

// InitialNEQ applies the NEQ predicate on the "Initial" field.
func InitialNEQ(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldInitial, v))
}

// InitialIn applies the In predicate on the "Initial" field.
func InitialIn(vs ...int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldInitial, vs...))
}

// InitialNotIn applies the NotIn predicate on the "Initial" field.
func InitialNotIn(vs ...int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldInitial, vs...))
}

// InitialIsNil applies the IsNil predicate on the "Initial" field.
func InitialIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldInitial))
}

// InitialNotNil applies the NotNil predicate on the "Initial" field.
func InitialNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldInitial))
}

// FirstNameEQ applies the EQ predicate on the "FirstName" field.
func FirstNameEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "FirstName" field.
func FirstNameNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "FirstName" field.
func FirstNameIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "FirstName" field.
func FirstNameNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "FirstName" field.
func FirstNameGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "FirstName" field.
func FirstNameGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "FirstName" field.
func FirstNameLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "FirstName" field.
func FirstNameLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "FirstName" field.
func FirstNameContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "FirstName" field.
func FirstNameHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "FirstName" field.
func FirstNameHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameEqualFold applies the EqualFold predicate on the "FirstName" field.
func FirstNameEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "FirstName" field.
func FirstNameContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldFirstName, v))
}

// MiddleNameEQ applies the EQ predicate on the "MiddleName" field.
func MiddleNameEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldMiddleName, v))
}

// MiddleNameNEQ applies the NEQ predicate on the "MiddleName" field.
func MiddleNameNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldMiddleName, v))
}

// MiddleNameIn applies the In predicate on the "MiddleName" field.
func MiddleNameIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldMiddleName, vs...))
}

// MiddleNameNotIn applies the NotIn predicate on the "MiddleName" field.
func MiddleNameNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldMiddleName, vs...))
}

// MiddleNameGT applies the GT predicate on the "MiddleName" field.
func MiddleNameGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldMiddleName, v))
}

// MiddleNameGTE applies the GTE predicate on the "MiddleName" field.
func MiddleNameGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldMiddleName, v))
}

// MiddleNameLT applies the LT predicate on the "MiddleName" field.
func MiddleNameLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldMiddleName, v))
}

// MiddleNameLTE applies the LTE predicate on the "MiddleName" field.
func MiddleNameLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldMiddleName, v))
}

// MiddleNameContains applies the Contains predicate on the "MiddleName" field.
func MiddleNameContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldMiddleName, v))
}

// MiddleNameHasPrefix applies the HasPrefix predicate on the "MiddleName" field.
func MiddleNameHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldMiddleName, v))
}

// MiddleNameHasSuffix applies the HasSuffix predicate on the "MiddleName" field.
func MiddleNameHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldMiddleName, v))
}

// MiddleNameIsNil applies the IsNil predicate on the "MiddleName" field.
func MiddleNameIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldMiddleName))
}

// MiddleNameNotNil applies the NotNil predicate on the "MiddleName" field.
func MiddleNameNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldMiddleName))
}

// MiddleNameEqualFold applies the EqualFold predicate on the "MiddleName" field.
func MiddleNameEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldMiddleName, v))
}

// MiddleNameContainsFold applies the ContainsFold predicate on the "MiddleName" field.
func MiddleNameContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldMiddleName, v))
}

// LastNameEQ applies the EQ predicate on the "LastName" field.
func LastNameEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldLastName, v))
}

// LastNameNEQ applies the NEQ predicate on the "LastName" field.
func LastNameNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldLastName, v))
}

// LastNameIn applies the In predicate on the "LastName" field.
func LastNameIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldLastName, vs...))
}

// LastNameNotIn applies the NotIn predicate on the "LastName" field.
func LastNameNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldLastName, vs...))
}

// LastNameGT applies the GT predicate on the "LastName" field.
func LastNameGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldLastName, v))
}

// LastNameGTE applies the GTE predicate on the "LastName" field.
func LastNameGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldLastName, v))
}

// LastNameLT applies the LT predicate on the "LastName" field.
func LastNameLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldLastName, v))
}

// LastNameLTE applies the LTE predicate on the "LastName" field.
func LastNameLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldLastName, v))
}

// LastNameContains applies the Contains predicate on the "LastName" field.
func LastNameContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldLastName, v))
}

// LastNameHasPrefix applies the HasPrefix predicate on the "LastName" field.
func LastNameHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldLastName, v))
}

// LastNameHasSuffix applies the HasSuffix predicate on the "LastName" field.
func LastNameHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldLastName, v))
}

// LastNameEqualFold applies the EqualFold predicate on the "LastName" field.
func LastNameEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldLastName, v))
}

// LastNameContainsFold applies the ContainsFold predicate on the "LastName" field.
func LastNameContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldLastName, v))
}

// ContactNumberEQ applies the EQ predicate on the "ContactNumber" field.
func ContactNumberEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldContactNumber, v))
}

// ContactNumberNEQ applies the NEQ predicate on the "ContactNumber" field.
func ContactNumberNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldContactNumber, v))
}

// ContactNumberIn applies the In predicate on the "ContactNumber" field.
func ContactNumberIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldContactNumber, vs...))
}

// ContactNumberNotIn applies the NotIn predicate on the "ContactNumber" field.
func ContactNumberNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldContactNumber, vs...))
}

// ContactNumberGT applies the GT predicate on the "ContactNumber" field.
func ContactNumberGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldContactNumber, v))
}

// ContactNumberGTE applies the GTE predicate on the "ContactNumber" field.
func ContactNumberGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldContactNumber, v))
}

// ContactNumberLT applies the LT predicate on the "ContactNumber" field.
func ContactNumberLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldContactNumber, v))
}

// ContactNumberLTE applies the LTE predicate on the "ContactNumber" field.
func ContactNumberLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldContactNumber, v))
}

// ContactNumberContains applies the Contains predicate on the "ContactNumber" field.
func ContactNumberContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldContactNumber, v))
}

// ContactNumberHasPrefix applies the HasPrefix predicate on the "ContactNumber" field.
func ContactNumberHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldContactNumber, v))
}

// ContactNumberHasSuffix applies the HasSuffix predicate on the "ContactNumber" field.
func ContactNumberHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldContactNumber, v))
}

// ContactNumberEqualFold applies the EqualFold predicate on the "ContactNumber" field.
func ContactNumberEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldContactNumber, v))
}

// ContactNumberContainsFold applies the ContainsFold predicate on the "ContactNumber" field.
func ContactNumberContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldContactNumber, v))
}

// EmailEQ applies the EQ predicate on the "Email" field.
func EmailEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "Email" field.
func EmailNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "Email" field.
func EmailIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "Email" field.
func EmailNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "Email" field.
func EmailGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "Email" field.
func EmailGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "Email" field.
func EmailLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "Email" field.
func EmailLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "Email" field.
func EmailContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "Email" field.
func EmailHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "Email" field.
func EmailHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "Email" field.
func EmailIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "Email" field.
func EmailNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "Email" field.
func EmailEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "Email" field.
func EmailContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldEmail, v))
}

// AgeEQ applies the EQ predicate on the "Age" field.
func AgeEQ(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldAge, v))
}

// AgeNEQ applies the NEQ predicate on the "Age" field.
func AgeNEQ(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldAge, v))
}

// AgeIn applies the In predicate on the "Age" field.
func AgeIn(vs ...int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldAge, vs...))
}

// AgeNotIn applies the NotIn predicate on the "Age" field.
func AgeNotIn(vs ...int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldAge, vs...))
}

// AgeGT applies the GT predicate on the "Age" field.
func AgeGT(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldAge, v))
}

// AgeGTE applies the GTE predicate on the "Age" field.
func AgeGTE(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldAge, v))
}

// AgeLT applies the LT predicate on the "Age" field.
func AgeLT(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldAge, v))
}

// AgeLTE applies the LTE predicate on the "Age" field.
func AgeLTE(v int) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldAge, v))
}

// AgeIsNil applies the IsNil predicate on the "Age" field.
func AgeIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldAge))
}

// AgeNotNil applies the NotNil predicate on the "Age" field.
func AgeNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldAge))
}

// PhotoIdUlidEQ applies the EQ predicate on the "PhotoId_ulid" field.
func PhotoIdUlidEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldPhotoIdUlid, v))
}

// PhotoIdUlidNEQ applies the NEQ predicate on the "PhotoId_ulid" field.
func PhotoIdUlidNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldPhotoIdUlid, v))
}

// PhotoIdUlidIn applies the In predicate on the "PhotoId_ulid" field.
func PhotoIdUlidIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldPhotoIdUlid, vs...))
}

// PhotoIdUlidNotIn applies the NotIn predicate on the "PhotoId_ulid" field.
func PhotoIdUlidNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldPhotoIdUlid, vs...))
}

// PhotoIdUlidGT applies the GT predicate on the "PhotoId_ulid" field.
func PhotoIdUlidGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldPhotoIdUlid, v))
}

// PhotoIdUlidGTE applies the GTE predicate on the "PhotoId_ulid" field.
func PhotoIdUlidGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldPhotoIdUlid, v))
}

// PhotoIdUlidLT applies the LT predicate on the "PhotoId_ulid" field.
func PhotoIdUlidLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldPhotoIdUlid, v))
}

// PhotoIdUlidLTE applies the LTE predicate on the "PhotoId_ulid" field.
func PhotoIdUlidLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldPhotoIdUlid, v))
}

// PhotoIdUlidContains applies the Contains predicate on the "PhotoId_ulid" field.
func PhotoIdUlidContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldPhotoIdUlid, v))
}

// PhotoIdUlidHasPrefix applies the HasPrefix predicate on the "PhotoId_ulid" field.
func PhotoIdUlidHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldPhotoIdUlid, v))
}

// PhotoIdUlidHasSuffix applies the HasSuffix predicate on the "PhotoId_ulid" field.
func PhotoIdUlidHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldPhotoIdUlid, v))
}

// PhotoIdUlidIsNil applies the IsNil predicate on the "PhotoId_ulid" field.
func PhotoIdUlidIsNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIsNull(FieldPhotoIdUlid))
}

// PhotoIdUlidNotNil applies the NotNil predicate on the "PhotoId_ulid" field.
func PhotoIdUlidNotNil() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotNull(FieldPhotoIdUlid))
}

// PhotoIdUlidEqualFold applies the EqualFold predicate on the "PhotoId_ulid" field.
func PhotoIdUlidEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldPhotoIdUlid, v))
}

// PhotoIdUlidContainsFold applies the ContainsFold predicate on the "PhotoId_ulid" field.
func PhotoIdUlidContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldPhotoIdUlid, v))
}

// AddressIdUlidEQ applies the EQ predicate on the "AddressId_ulid" field.
func AddressIdUlidEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEQ(FieldAddressIdUlid, v))
}

// AddressIdUlidNEQ applies the NEQ predicate on the "AddressId_ulid" field.
func AddressIdUlidNEQ(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNEQ(FieldAddressIdUlid, v))
}

// AddressIdUlidIn applies the In predicate on the "AddressId_ulid" field.
func AddressIdUlidIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldIn(FieldAddressIdUlid, vs...))
}

// AddressIdUlidNotIn applies the NotIn predicate on the "AddressId_ulid" field.
func AddressIdUlidNotIn(vs ...string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldNotIn(FieldAddressIdUlid, vs...))
}

// AddressIdUlidGT applies the GT predicate on the "AddressId_ulid" field.
func AddressIdUlidGT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGT(FieldAddressIdUlid, v))
}

// AddressIdUlidGTE applies the GTE predicate on the "AddressId_ulid" field.
func AddressIdUlidGTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldGTE(FieldAddressIdUlid, v))
}

// AddressIdUlidLT applies the LT predicate on the "AddressId_ulid" field.
func AddressIdUlidLT(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLT(FieldAddressIdUlid, v))
}

// AddressIdUlidLTE applies the LTE predicate on the "AddressId_ulid" field.
func AddressIdUlidLTE(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldLTE(FieldAddressIdUlid, v))
}

// AddressIdUlidContains applies the Contains predicate on the "AddressId_ulid" field.
func AddressIdUlidContains(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContains(FieldAddressIdUlid, v))
}

// AddressIdUlidHasPrefix applies the HasPrefix predicate on the "AddressId_ulid" field.
func AddressIdUlidHasPrefix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasPrefix(FieldAddressIdUlid, v))
}

// AddressIdUlidHasSuffix applies the HasSuffix predicate on the "AddressId_ulid" field.
func AddressIdUlidHasSuffix(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldHasSuffix(FieldAddressIdUlid, v))
}

// AddressIdUlidEqualFold applies the EqualFold predicate on the "AddressId_ulid" field.
func AddressIdUlidEqualFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldEqualFold(FieldAddressIdUlid, v))
}

// AddressIdUlidContainsFold applies the ContainsFold predicate on the "AddressId_ulid" field.
func AddressIdUlidContainsFold(v string) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.FieldContainsFold(FieldAddressIdUlid, v))
}

// HasUser applies the HasEdge predicate on the "User" edge.
func HasUser() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "User" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.TblUSers) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNameInitial applies the HasEdge predicate on the "NameInitial" edge.
func HasNameInitial() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, NameInitialTable, NameInitialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNameInitialWith applies the HasEdge predicate on the "NameInitial" edge with a given conditions (other predicates).
func HasNameInitialWith(preds ...predicate.TblEnum) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := newNameInitialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnerPhoto applies the HasEdge predicate on the "OwnerPhoto" edge.
func HasOwnerPhoto() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerPhotoTable, OwnerPhotoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerPhotoWith applies the HasEdge predicate on the "OwnerPhoto" edge with a given conditions (other predicates).
func HasOwnerPhotoWith(preds ...predicate.TblDocument) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := newOwnerPhotoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAddress applies the HasEdge predicate on the "Address" edge.
func HasAddress() predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AddressTable, AddressColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAddressWith applies the HasEdge predicate on the "Address" edge with a given conditions (other predicates).
func HasAddressWith(preds ...predicate.TblAddress) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(func(s *sql.Selector) {
		step := newAddressStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TblGarageOwner) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TblGarageOwner) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TblGarageOwner) predicate.TblGarageOwner {
	return predicate.TblGarageOwner(sql.NotPredicates(p))
}
