// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"rr-backend/ent/entgen/predicate"
	"rr-backend/ent/entgen/tblusers"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TblUSersDelete is the builder for deleting a TblUSers entity.
type TblUSersDelete struct {
	config
	hooks    []Hook
	mutation *TblUSersMutation
}

// Where appends a list predicates to the TblUSersDelete builder.
func (tud *TblUSersDelete) Where(ps ...predicate.TblUSers) *TblUSersDelete {
	tud.mutation.Where(ps...)
	return tud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tud *TblUSersDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tud.sqlExec, tud.mutation, tud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tud *TblUSersDelete) ExecX(ctx context.Context) int {
	n, err := tud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tud *TblUSersDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tblusers.Table, sqlgraph.NewFieldSpec(tblusers.FieldID, field.TypeString))
	if ps := tud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tud.mutation.done = true
	return affected, err
}

// TblUSersDeleteOne is the builder for deleting a single TblUSers entity.
type TblUSersDeleteOne struct {
	tud *TblUSersDelete
}

// Where appends a list predicates to the TblUSersDelete builder.
func (tudo *TblUSersDeleteOne) Where(ps ...predicate.TblUSers) *TblUSersDeleteOne {
	tudo.tud.mutation.Where(ps...)
	return tudo
}

// Exec executes the deletion query.
func (tudo *TblUSersDeleteOne) Exec(ctx context.Context) error {
	n, err := tudo.tud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tblusers.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tudo *TblUSersDeleteOne) ExecX(ctx context.Context) {
	if err := tudo.Exec(ctx); err != nil {
		panic(err)
	}
}
