// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TblSuperAdminColumns holds the columns for the "Tbl_SuperAdmin" table.
	TblSuperAdminColumns = []*schema.Column{
		{Name: "Id_ulid", Type: field.TypeString, Size: 40},
		{Name: "CreatedBy", Type: field.TypeString, Nullable: true, Size: 40},
		{Name: "UpdatedBy", Type: field.TypeString, Nullable: true, Size: 40},
		{Name: "DeletedBy", Type: field.TypeString, Nullable: true, Size: 40},
		{Name: "IP", Type: field.TypeString, Nullable: true},
		{Name: "UserAgent", Type: field.TypeString, Nullable: true},
		{Name: "CreatedAt", Type: field.TypeTime},
		{Name: "UpdatedAt", Type: field.TypeTime},
		{Name: "DeletedAt", Type: field.TypeTime, Nullable: true},
		{Name: "UserName", Type: field.TypeString, Size: 40},
		{Name: "PassWord", Type: field.TypeString, Size: 40},
	}
	// TblSuperAdminTable holds the schema information for the "Tbl_SuperAdmin" table.
	TblSuperAdminTable = &schema.Table{
		Name:       "Tbl_SuperAdmin",
		Columns:    TblSuperAdminColumns,
		PrimaryKey: []*schema.Column{TblSuperAdminColumns[0]},
	}
	// TblUsersColumns holds the columns for the "Tbl_Users" table.
	TblUsersColumns = []*schema.Column{
		{Name: "Id_ulid", Type: field.TypeString, Size: 40},
		{Name: "CreatedBy", Type: field.TypeString, Nullable: true, Size: 40},
		{Name: "UpdatedBy", Type: field.TypeString, Nullable: true, Size: 40},
		{Name: "DeletedBy", Type: field.TypeString, Nullable: true, Size: 40},
		{Name: "IP", Type: field.TypeString, Nullable: true},
		{Name: "UserAgent", Type: field.TypeString, Nullable: true},
		{Name: "CreatedAt", Type: field.TypeTime},
		{Name: "UpdatedAt", Type: field.TypeTime},
		{Name: "DeletedAt", Type: field.TypeTime, Nullable: true},
		{Name: "UserName", Type: field.TypeString, Size: 40},
		{Name: "Password", Type: field.TypeString, Size: 40},
		{Name: "Email", Type: field.TypeString, Nullable: true, Size: 40},
	}
	// TblUsersTable holds the schema information for the "Tbl_Users" table.
	TblUsersTable = &schema.Table{
		Name:       "Tbl_Users",
		Columns:    TblUsersColumns,
		PrimaryKey: []*schema.Column{TblUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TblSuperAdminTable,
		TblUsersTable,
	}
)

func init() {
	TblSuperAdminTable.Annotation = &entsql.Annotation{
		Table: "Tbl_SuperAdmin",
	}
	TblUsersTable.Annotation = &entsql.Annotation{
		Table: "Tbl_Users",
	}
}
