// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TblSuperAdmin is the predicate function for tblsuperadmin builders.
type TblSuperAdmin func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
