// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TblSuperAdmin is the predicate function for tblsuperadmin builders.
type TblSuperAdmin func(*sql.Selector)

// TblUSers is the predicate function for tblusers builders.
type TblUSers func(*sql.Selector)
