// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"
	"rr-backend/ent/entgen"
	"rr-backend/ent/entgen/predicate"
	"rr-backend/ent/entgen/tbladdress"
	"rr-backend/ent/entgen/tbldocument"
	"rr-backend/ent/entgen/tblenum"
	"rr-backend/ent/entgen/tblgarageowner"
	"rr-backend/ent/entgen/tblsuperadmin"
	"rr-backend/ent/entgen/tblusers"

	"entgo.io/ent/dialect/sql"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next entgen.Querier) entgen.Querier {
	return entgen.QuerierFunc(func(ctx context.Context, q entgen.Query) (entgen.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q entgen.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The TblAddressFunc type is an adapter to allow the use of ordinary function as a Querier.
type TblAddressFunc func(context.Context, *entgen.TblAddressQuery) (entgen.Value, error)

// Query calls f(ctx, q).
func (f TblAddressFunc) Query(ctx context.Context, q entgen.Query) (entgen.Value, error) {
	if q, ok := q.(*entgen.TblAddressQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *entgen.TblAddressQuery", q)
}

// The TraverseTblAddress type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTblAddress func(context.Context, *entgen.TblAddressQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTblAddress) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTblAddress) Traverse(ctx context.Context, q entgen.Query) error {
	if q, ok := q.(*entgen.TblAddressQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *entgen.TblAddressQuery", q)
}

// The TblDocumentFunc type is an adapter to allow the use of ordinary function as a Querier.
type TblDocumentFunc func(context.Context, *entgen.TblDocumentQuery) (entgen.Value, error)

// Query calls f(ctx, q).
func (f TblDocumentFunc) Query(ctx context.Context, q entgen.Query) (entgen.Value, error) {
	if q, ok := q.(*entgen.TblDocumentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *entgen.TblDocumentQuery", q)
}

// The TraverseTblDocument type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTblDocument func(context.Context, *entgen.TblDocumentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTblDocument) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTblDocument) Traverse(ctx context.Context, q entgen.Query) error {
	if q, ok := q.(*entgen.TblDocumentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *entgen.TblDocumentQuery", q)
}

// The TblEnumFunc type is an adapter to allow the use of ordinary function as a Querier.
type TblEnumFunc func(context.Context, *entgen.TblEnumQuery) (entgen.Value, error)

// Query calls f(ctx, q).
func (f TblEnumFunc) Query(ctx context.Context, q entgen.Query) (entgen.Value, error) {
	if q, ok := q.(*entgen.TblEnumQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *entgen.TblEnumQuery", q)
}

// The TraverseTblEnum type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTblEnum func(context.Context, *entgen.TblEnumQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTblEnum) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTblEnum) Traverse(ctx context.Context, q entgen.Query) error {
	if q, ok := q.(*entgen.TblEnumQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *entgen.TblEnumQuery", q)
}

// The TblGarageOwnerFunc type is an adapter to allow the use of ordinary function as a Querier.
type TblGarageOwnerFunc func(context.Context, *entgen.TblGarageOwnerQuery) (entgen.Value, error)

// Query calls f(ctx, q).
func (f TblGarageOwnerFunc) Query(ctx context.Context, q entgen.Query) (entgen.Value, error) {
	if q, ok := q.(*entgen.TblGarageOwnerQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *entgen.TblGarageOwnerQuery", q)
}

// The TraverseTblGarageOwner type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTblGarageOwner func(context.Context, *entgen.TblGarageOwnerQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTblGarageOwner) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTblGarageOwner) Traverse(ctx context.Context, q entgen.Query) error {
	if q, ok := q.(*entgen.TblGarageOwnerQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *entgen.TblGarageOwnerQuery", q)
}

// The TblSuperAdminFunc type is an adapter to allow the use of ordinary function as a Querier.
type TblSuperAdminFunc func(context.Context, *entgen.TblSuperAdminQuery) (entgen.Value, error)

// Query calls f(ctx, q).
func (f TblSuperAdminFunc) Query(ctx context.Context, q entgen.Query) (entgen.Value, error) {
	if q, ok := q.(*entgen.TblSuperAdminQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *entgen.TblSuperAdminQuery", q)
}

// The TraverseTblSuperAdmin type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTblSuperAdmin func(context.Context, *entgen.TblSuperAdminQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTblSuperAdmin) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTblSuperAdmin) Traverse(ctx context.Context, q entgen.Query) error {
	if q, ok := q.(*entgen.TblSuperAdminQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *entgen.TblSuperAdminQuery", q)
}

// The TblUSersFunc type is an adapter to allow the use of ordinary function as a Querier.
type TblUSersFunc func(context.Context, *entgen.TblUSersQuery) (entgen.Value, error)

// Query calls f(ctx, q).
func (f TblUSersFunc) Query(ctx context.Context, q entgen.Query) (entgen.Value, error) {
	if q, ok := q.(*entgen.TblUSersQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *entgen.TblUSersQuery", q)
}

// The TraverseTblUSers type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTblUSers func(context.Context, *entgen.TblUSersQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTblUSers) Intercept(next entgen.Querier) entgen.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTblUSers) Traverse(ctx context.Context, q entgen.Query) error {
	if q, ok := q.(*entgen.TblUSersQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *entgen.TblUSersQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q entgen.Query) (Query, error) {
	switch q := q.(type) {
	case *entgen.TblAddressQuery:
		return &query[*entgen.TblAddressQuery, predicate.TblAddress, tbladdress.OrderOption]{typ: entgen.TypeTblAddress, tq: q}, nil
	case *entgen.TblDocumentQuery:
		return &query[*entgen.TblDocumentQuery, predicate.TblDocument, tbldocument.OrderOption]{typ: entgen.TypeTblDocument, tq: q}, nil
	case *entgen.TblEnumQuery:
		return &query[*entgen.TblEnumQuery, predicate.TblEnum, tblenum.OrderOption]{typ: entgen.TypeTblEnum, tq: q}, nil
	case *entgen.TblGarageOwnerQuery:
		return &query[*entgen.TblGarageOwnerQuery, predicate.TblGarageOwner, tblgarageowner.OrderOption]{typ: entgen.TypeTblGarageOwner, tq: q}, nil
	case *entgen.TblSuperAdminQuery:
		return &query[*entgen.TblSuperAdminQuery, predicate.TblSuperAdmin, tblsuperadmin.OrderOption]{typ: entgen.TypeTblSuperAdmin, tq: q}, nil
	case *entgen.TblUSersQuery:
		return &query[*entgen.TblUSersQuery, predicate.TblUSers, tblusers.OrderOption]{typ: entgen.TypeTblUSers, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
